version: '3.8'

services:
  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    depends_on:
      - directus    
    ports:
      - 5173:5173
    working_dir: /app
    command: npm run setup

  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./directus/data/database:/var/lib/postgresql/data
      - ./directus/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.6.2
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'
      CACHE_PERMISSIONS: 'true'
      CACHE_SCHEMA: 'true'
      CACHE_AUTO_PURGE: 'true'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'